# Adapted from https://david.dev/how-to-install-mariadb-phpmyadmin-with-docker-compose 

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    expose:
      - "40000"
    ports:
      - "40000:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./footcal-db-dump:/docker-entrypoint-initdb.d
    networks:
      db:


  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db:
